name: GloriaDei
favicon: null
layout_spectrum: 0.7553192
typography_spectrum: 0.1531915
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Baptistengemeinde Gloria Dei Gleisdorf
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161417'
    - '#6F6654'
    - '#D7CEC6'
    - '#FFFFFB'
    - '#651528'
  brandStrength: 1
  lightness: 0.6468085
  saturation: 0.3595745
  rhythmicContrast: 0.8066034
purpose: []
