collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1531915
color:
  saturation: 0.3595745
  brandStrength: 1
  rhythmicContrast: 0.8066034
  brandColors:
    - '#161417'
    - '#6F6654'
    - '#D7CEC6'
    - '#FFFFFB'
    - '#651528'
  lightness: 0.6468085
layout_spectrum: 0.7553192
name: GloriaDei
